name: First pipeline

on:
    push:
        branches: ["master"]

jobs:
    test: 
        runs-on: ubuntu-latest
        steps: 
            # - uses: actions/checkout@v3 
            - uses: "shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e"
              with:
                php-version: '8.1'    
            - uses: "actions/checkout@v3"
            - name: "Copy .env"
              run: |
                    cd api
                    cp .env.ci .env
            - name: "Install Dependencies"
              run: |
                  cd api
                  composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Generate key
              run: |
                cd api
                php artisan key:generate
            - name: Directory Permissions
              run: |
                cd api
                chmod -R 777 storage bootstrap/cache
            - name: phpstan
              run: |
                cd api
                ./vendor/bin/phpstan analyse --memory-limit=1G
            - name: phpinsights
              run: |
                cd api
                php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 --ansi --format=github-action
            # - name: Run tests
            #   run: |
            #     cd api
            #     php artisan test

                
