name: First pipeline

on:
    push:
        branches: ["master"]

jobs:
    test: 
        runs-on: ubuntu-latest
        steps: 
            # - uses: actions/checkout@v3 
            - uses: "shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e"
              with:
                php-version: '8.1'    
            - uses: "actions/checkout@v3"
            - name: "Copy .env"
              run: |
                    cd api
                    cp .env.ci .env


                
